Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 10

Metrics/ModuleLength:
  Max: 600

Rails/HasAndBelongsToMany:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'Gemfile.lock'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'config/initializers/**/*'
    - 'test/test_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Rails:
  Enabled: true
