default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: julinha

development:
  <<: *default
  database: eloquent_repositories_development

test:
  <<: *default
  database: eloquent_repositories_test
